First commit of bump 0.0.2

diff --git a/miniQV b/miniQV
--- a/miniQV
+++ b/miniQV
@@ -1,6 +1,6 @@
 #!/bin/bash
 set -a	## EXPORT ALL FUNCTIONS TOO
-set -e  ## exit when any command fails
+##set -e  ## exit when any command fails : now commented out since it prevents some error catches and subsequent help messages.
 #########################################################################################################
 
 
@@ -20,6 +20,7 @@ export UTILS=${SCRIPTDIR}/utils
 export PYSCRIPTS=${UTILS}/miniqvpy
 export PATH=${UTILS}:${PYSCRIPTS}:${PATH}
 export PYTHONPATH=${UTILS}:${PYSCRIPTS}:${PYTHONPATH}
+export EXEDIR=${PWD}
 
 ## TO REMOVE
 export PATH=~/software/seqtk/seqtk/:~/software/samtools/localinstall/bin/:~/software/minimap2/minimap2/:${PATH}
@@ -67,7 +68,7 @@ export TRIM3=0
 export SAVESAM=false
 export SAMOUT=""
 export FORCESORT=false
-
+export WDNAME=miniqv_output
 export VERBOSE=false
 export A=false
 export B=false
@@ -76,7 +77,7 @@ export TIME=6:00:00    ## SLURM option
 export MEM=6G          ## SLURM option
 
 
-while getopts "a:b:fr:d:m:x:t:H:s:n:ST:M:W:Nv" arg; do
+while getopts "a:b:fr:d:m:x:t:H:s:n:ST:M:W:No:v" arg; do
     case $arg in
 	a) export INPUT=${OPTARG} ; export BAMMODE=false ; A=true ;; 		## if it is FOFN, then 2- or 3-columns and need -F flag; autodetects 2- vs 3- ; otherwise this is a asm FASTA
         b) export INPUT=${OPTARG} ; export BAMMODE=true ; B=true ;; 		## if it is FOFN, then 2- or 3-columns and need -F flag; autodetects 2- vs 3- ; otherwise this is a BAM
@@ -94,6 +95,7 @@ while getopts "a:b:fr:d:m:x:t:H:s:n:ST:M:W:Nv" arg; do
 	M) export MEM=${OPTARG} ;;
 	W) export SAMOUT=${OPTARG} ; SAVESAM=true ;;
 	N) export FORCESORT=true ;; 
+	o) export WDNAME=${OPTARG} ;;
 	v) export VERBOSE=true ;;
         *) help; exit;;
     esac
@@ -102,7 +104,6 @@ done
 
 #####	X) export MAXINS=${OPTARG} ;;
 
-
 #########################################################################################################
 ## INTERPRET CMDLINE ARGS TO REJECT ERRORS AND SET VARS
 #########################################################################################################
@@ -110,9 +111,10 @@ if $A && $B ; then echo "Please specify only -a or -b. Exiting..." ; exit ; fi
 if ${FOFNMODE}; then export FOFN=${INPUT} ; fi
 
 #########################################################################################################
-## INTERPRET CMDLINE ARGS TO 
+## INTERPRET CMDLINE ARGS TO GET ABS PATH FOR INPUT
 #########################################################################################################
-
+update_input
+update_reads
 
 #########################################################################################################
 ## INTERPRET CMDLINE ARGS TO MAKE SURE MAPPER PRESENT
@@ -148,6 +150,7 @@ select_map_fxn
 
 for REQUIRED in seqtk samtools ; do TOOL=$( which ${REQUIRED} ) ; if [ -z ${TOOL} ]; then echo "${REQUIRED} not found. Put it in your PATH and try again." ; exit ; fi ; done
 
+
 for PROVIDED in samPctIdentity.py stats.py ; do TOOL=$( which ${PROVIDED} ) ; 
 if [ -z ${TOOL} ]; then echo "${PROVIDED} was not found, although it comes packaged with MiniQV in the utils directory. Something is wrong internally. As a user, you should never see this message. My deepest condolences. Have at me with a GitHub issue." ; exit ; fi ; done
 
@@ -155,7 +158,7 @@ for REQOPT in INPUT READS ; do if [ -z ${REQOPT} ]; then echo "${!REQOPT} was no
 
 #for OPT in INPUT READS FOFNMODE DATATYPE MAPPER BTMODE MAPFXN THREADS GLOBAL_HET_RATE SKIP_N UPTO_N SLURM TIME MEM SAVESAM SAMOUT FORCESORT VERBOSE ; do echo -e "${OPT}\t${!OPT}" ; done
 
-ALLVARS="SCRIPTDIR UTILS PYSCRIPTS PATH PYTHONPATH INPUT READS R1 FOFN DATATYPE MAPPER BTMODE MAPFXN BAMMODE FOFNMODE THREADS P GLOBAL_HET_RATE HET_RATE_NOT_PROVIDED SKIP_N UPTO_N SAVESAM SAMOUT FORCESORT VERBOSE SLURM TIME MEM MINIMAP2 BT2 BUILD MAGIC MAGICBUILD"
+ALLVARS="SCRIPTDIR UTILS PYSCRIPTS PATH PYTHONPATH EXEDIR INPUT_GIVEN INPUT READS_GIVEN READS R1 FOFN DATATYPE MAPPER BTMODE MAPFXN BAMMODE FOFNMODE THREADS P GLOBAL_HET_RATE HET_RATE_NOT_PROVIDED SKIP_N UPTO_N SAVESAM SAMOUT FORCESORT VERBOSE SLURM TIME MEM MINIMAP2 BT2 BUILD MAGIC MAGICBUILD"
 for OPT in ${ALLVARS} ; do echo -e "${OPT}\t${!OPT}" ; done
 
 if $HET_RATE_NOT_PROVIDED ; then echo -e "Warning: a heterozygosity rate was not provided. The default of ${GLOBAL_HET_RATE} is being used. Ultimately, this means that you should not use the QVs computed after subtracting errors due to heterozygosity (unless the expected het rate is close to the default used).\n" ; fi
